### ISSUE TITLE
[BUG] Camera Resolution is 640x480 on Fire HD 10 gen 7 and 9, also very dark picture

### ISSUE THREAD

**Issue by mannebk79** [TheTimeWalker/wallpanel-android#67] opened 2023-01-30 15:57 UTC
**Describe the bug**
On several separate Amazon Fire HD 10 gen 7 and also on one gen 9 I have, with the current version, and also with all old versions even from thanksmister, the issue that the cam only finds 640x480 as resolution but the spec for the devices give way more megapixles. 

It does not matter if i select front or back camera

Picture is very dark and basically unusable.

I gladly supply what is needed for troubleshooting in form of logs or what ever or even send the hardware for testing.

**Comment by TheTimeWalker** [comment] 2023-01-30 17:25
Duplicate of #6 ... by you!

**Closed by TheTimeWalker** 2023-01-30 17:25 UTC
